addons:
  apt:
    packages:
      - rake
      - git
      - bison
      - gperf
      - libonig-dev
language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=1.4.1
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
script:
  - rake test
